# Generated by Django 3.2.25 on 2025-08-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
