# Generated by Django 3.2.25 on 2025-08-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20250825_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Club',
            new_name='Clubs',
        ),
    ]
