# Generated by Django 3.2.25 on 2025-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_rename_club_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
