# Generated by Django 3.2.25 on 2025-08-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_auto_20250829_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institute.career'),
        ),
    ]
