# Generated by Django 3.2.25 on 2025-08-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_alter_user_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='djangopass', max_length=128),
        ),
    ]
